//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cashier
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTransactionItem
    {
        public int TransactionItemId { get; set; }
        public int TransactionId { get; set; }
        public int ProductId { get; set; }
    
        public virtual TblProduct TblProduct { get; set; }
        public virtual TblTransaction TblTransaction { get; set; }
    }
}
